version: '3.8'

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=fangying
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app

volumes:
  app-db-data: