// This file is auto-generated by @hey-api/openapi-ts
import { ApiError } from "./core/ApiError"
import { OpenAPI } from "./core/OpenAPI"

export { ApiError } from "./core/ApiError"
export { CancelablePromise, CancelError } from "./core/CancelablePromise"
export { OpenAPI, type OpenAPIConfig } from "./core/OpenAPI"
export * from "./sdk.gen"
export * from "./types.gen"

export interface ApiKey {
  id: number
  name: string
  key?: string
  created_at: string
  is_active: boolean
}

export interface CreateApiKeyRequest {
  name: string
}

export class ApiKeysService {
  static async listApiKeys(): Promise<ApiKey[]> {
    try {
      const response = await fetch(`${OpenAPI.BASE}/api/keys`, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${await OpenAPI.TOKEN()}`,
          'Content-Type': 'application/json',
        },
      })
      if (!response.ok) {
        const error = await response.json()
        throw new ApiError(response, error.detail || 'Failed to fetch keys')
      }
      return response.json()
    } catch (error) {
      if (error instanceof ApiError) throw error
      throw new ApiError(undefined, 'Network error')
    }
  }

  static async createApiKey(data: CreateApiKeyRequest): Promise<ApiKey> {
    try {
      const response = await fetch(`${OpenAPI.BASE}/api/keys`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${await OpenAPI.TOKEN()}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      })
      if (!response.ok) {
        const error = await response.json()
        throw new ApiError(response, error.detail || 'Failed to create key')
      }
      return response.json()
    } catch (error) {
      if (error instanceof ApiError) throw error
      throw new ApiError(undefined, 'Network error')
    }
  }

  static async deleteApiKey(id: number): Promise<void> {
    try {
      const response = await fetch(`${OpenAPI.BASE}/api/keys/${id}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${await OpenAPI.TOKEN()}`,
          'Content-Type': 'application/json',
        },
      })
      if (!response.ok) {
        const error = await response.json()
        throw new ApiError(response, error.detail || 'Failed to delete key')
      }
    } catch (error) {
      if (error instanceof ApiError) throw error
      throw new ApiError(undefined, 'Network error')
    }
  }

  static async toggleApiKey(id: number): Promise<ApiKey> {
    try {
      const response = await fetch(`${OpenAPI.BASE}/api/keys/${id}/toggle`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${await OpenAPI.TOKEN()}`,
          'Content-Type': 'application/json',
        },
      })
      if (!response.ok) {
        const error = await response.json()
        throw new ApiError(response, error.detail || 'Failed to toggle key')
      }
      return response.json()
    } catch (error) {
      if (error instanceof ApiError) throw error
      throw new ApiError(undefined, 'Network error')
    }
  }
}
