"""add api keys table

Revision ID: 24be305df856
Revises: 2e3b124a4378
Create Date: 2024-12-23 21:56:40.910622

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '24be305df856'
down_revision = '2e3b124a4378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint('apikey_owner_id_fkey', 'apikey', type_='foreignkey')
    op.create_foreign_key(None, 'apikey', 'user', ['user_id'], ['id'])
    op.drop_column('apikey', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'apikey', type_='foreignkey')
    op.create_foreign_key('apikey_owner_id_fkey', 'apikey', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('apikey', 'user_id')
    # ### end Alembic commands ###
