"""add api keys table

Revision ID: 7bd02b2b36d6
Revises: 0090b518433f
Create Date: 2024-12-23 00:59:26.359727

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7bd02b2b36d6'
down_revision = '0090b518433f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
