"""add api keys table

Revision ID: 92c5cab39f57
Revises: bc9ee8ef2f75
Create Date: 2024-12-22 22:53:35.953916

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92c5cab39f57'
down_revision = 'bc9ee8ef2f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
