"""Your migration message

Revision ID: bc9ee8ef2f75
Revises: ee26e3da31c4
Create Date: 2024-12-22 21:56:10.271346

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc9ee8ef2f75'
down_revision = 'ee26e3da31c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
