"""add api keys table

Revision ID: e28df5849de8
Revises: a24769841bd8
Create Date: 2024-12-24 00:29:04.672026

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e28df5849de8'
down_revision = 'a24769841bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('item_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'apikey', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apikey', type_='foreignkey')
    op.drop_column('apikey', 'item_id')
    # ### end Alembic commands ###
