"""Your migration message

Revision ID: ee26e3da31c4
Revises: 1a31ce608336
Create Date: 2024-12-22 21:45:02.150055

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee26e3da31c4'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('machine_info', sa.JSON(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_key'), 'licenses', ['key'], unique=True)
    op.create_index(op.f('ix_licenses_unique_id'), 'licenses', ['unique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenses_unique_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_key'), table_name='licenses')
    op.drop_table('licenses')
    # ### end Alembic commands ###
